version: "3.8"

networks:
  mynetwork:
    driver: bridge

volumes:
  WP:
    driver: local
    name: WP
    driver_opts:
      type: none
      o : bind
      device: /home/ael-beka/data/wordpress/
  MDB:
    driver: local
    name : MDB
    driver_opts:
      type: none
      o: bind
      device: /home/ael-beka/data/mariadb/

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - WP:/var/www/html
    restart: always
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - ./.env
    depends_on:
      - mariadb
    volumes:
      - WP:/var/www/html
    restart: always
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - ./.env
    volumes:
      - MDB:/var/lib/mysql
    restart: always
    networks:
      - mynetwork